[project]
name = "fraxis"
authors = [
    { name = "Picurit", email = "dev@picurit.com"}
]
description = "Bidirectional axis for full CRUD Frappe-Database operations trough Socket IO"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
    "python-socketio>=5.13,<5.14",
    "uvicorn>=0.38,<0.39",
    "uvloop>=0.22,<0.23",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
